const companies = [
  { logo: "../logos/Accenture.png" },
  { logo: "/logos/Adobe.png" },
  { logo: "/logos/Amazon.png" },
  { logo: "/logos/Apple.png" },
  { logo: "/logos/Axis Bank.jpg" },
  { logo: "/logos/Byjus.png" },
  { logo: "/logos/Capgemini.png" },
  { logo: "/logos/Cognizant.jpg" },
  { logo: "/logos/Concentrix.png" },
  { logo: "/logos/Dell.png" },
  { logo: "/logos/Deloitte.png" },
  { logo: "/logos/EY.png" },
  { logo: "/logos/Flipkart.jpg" },
  { logo: "/logos/Freshworks.jpg" },
  { logo: "/logos/Genpact.png" },
   { logo: "/logos/JPMorganChase.png" },
  { logo: "/logos/GoldmanSachs.png" },
  { logo: "/logos/Google.png" },
  { logo: "/logos/HCL.png" },
  { logo: "/logos/HDFC.jpg" },
  { logo: "/logos/IBM.png" },
  { logo: "/logos/ICICI.jpg" },
  { logo: "/logos/Infosys.png" },
  { logo: "/logos/Itimindtree.png" },
  { logo: "/logos/KPMG.png" },
  { logo: "/logos/LinkedIn.png" },
  { logo: "/logos/Meta.png" },
  { logo: "/logos/Microsoft.png" },
  { logo: "/logos/Mindtree.png" },
  { logo: "/logos/Morganstanley.png" },
  { logo: "/logos/Mphasis.png" },
  { logo: "/logos/Netflix.png" },
  { logo: "/logos/Oracle.png" },
  { logo: "/logos/Paytm.png" },
  { logo: "/logos/Phonepe.png" },
  { logo: "/logos/PWS.png" },
  { logo: "/logos/Swiggy.png" },
  { logo: "/logos/TCS.jpg" },
  { logo: "/logos/TechMahindra.png" },
  { logo: "/logos/Teleperformance.png" },
  { logo: "/logos/Unacademy.png" },
  { logo: "/logos/Wipro.png" },
  { logo: "/logos/ZensarTechnologies.jpg" },
  { logo: "/logos/Zomato.png" }
];

export default companies;