const jobs = [
  {
    id: 1,
    title: "Customer Support Executive",
    company: "Amazon India",
    location: "Hyderabad",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Communication","CRM","Problem Solving","Email Support"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-16",
    logo: "/logos/Amazon.png"
  },

  {
    id: 2,
    title: "Customer Support Executive",
    company: "Flipkart",
    location: "Bengaluru",
    salary: "3-5 LPA",
    experience: "0-2 Years",
    type: "Full Time",
    skills: ["Chat Support","CRM","Customer Handling","Communication"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-16",
    logo: "/logos/Flipkart.jpg"
  },

  {
    id: 3,
    title: "Customer Support Executive",
    company: "Paytm",
    location: "Noida",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Voice Support","CRM","Problem Solving","Communication"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-15",
    logo: "/logos/Paytm.png"
  },

  {
    id: 4,
    title: "Customer Support Executive",
    company: "Zomato",
    location: "Gurgaon",
    salary: "3-5 LPA",
    experience: "0-2 Years",
    type: "Full Time",
    skills: ["Chat Support","Customer Handling","CRM","Communication"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-15",
    logo: "/logos/Zomato.png"
  },

  {
    id: 5,
    title: "Customer Support Executive",
    company: "Swiggy",
    location: "Bengaluru",
    salary: "3-5 LPA",
    experience: "0-2 Years",
    type: "Full Time",
    skills: ["Support Chat","CRM","Problem Solving","Communication"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-14",
    logo: "/logos/Swiggy.png"
  },

  {
    id: 6,
    title: "Customer Support Executive",
    company: "BYJU'S",
    location: "Bengaluru",
    salary: "3-7 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Calling","CRM","Communication","Lead Support"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-14",
    logo: "/logos/Byjus.png"
  },

  {
    id: 7,
    title: "Customer Support Executive",
    company: "Infosys BPM",
    location: "Pune",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Voice Process","CRM","Email Support","Communication"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-13",
    logo: "/logos/Infosys.png"
  },

  {
    id: 8,
    title: "Customer Support Executive",
    company: "Wipro BPO",
    location: "Chennai",
    salary: "3-5 LPA",
    experience: "0-2 Years",
    type: "Full Time",
    skills: ["Chat Support","CRM","English Communication","Typing"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-13",
    logo: "/logos/Wipro.png"
  },

  {
    id: 9,
    title: "Customer Support Executive",
    company: "TCS BPS",
    location: "Hyderabad",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Voice Support","CRM","Customer Handling","Communication"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-12",
    logo: "/logos/TCS.jpg"
  },

  {
    id: 10,
    title: "Customer Support Executive",
    company: "Concentrix",
    location: "Mumbai",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Customer Service","CRM","Voice Process","Communication"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-12",
    logo: "/logos/Concentrix.png"
  },

  {
    id: 11,
    title: "Customer Support Executive",
    company: "Teleperformance",
    location: "Gurgaon",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Voice Support","CRM","Problem Solving","Communication"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-11",
    logo: "/logos/Teleperformance.png"
  },

  {
    id: 12,
    title: "Customer Support Executive",
    company: "HCL Technologies",
    location: "Noida",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Email Support","CRM","Voice Process","Communication"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-11",
    logo: "/logos/HCL.png"
  },

  {
    id: 13,
    title: "Customer Support Executive",
    company: "Capgemini",
    location: "Pune",
    salary: "3-5 LPA",
    experience: "0-2 Years",
    type: "Full Time",
    skills: ["Chat Support","CRM","Communication","Typing"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-10",
    logo: "/logos/Capgemini.png"
  },

  {
    id: 14,
    title: "Customer Support Executive",
    company: "Accenture",
    location: "Bengaluru",
    salary: "4-7 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Customer Service","CRM","Voice Support","Communication"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-10",
    logo: "/logos/Accenture.png"
  },

  {
    id: 15,
    title: "Customer Support Executive",
    company: "Tech Mahindra",
    location: "Noida",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Voice Process","CRM","Problem Solving","Communication"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-09",
    logo: "/logos/TechMahindra.png"
  },

  {
    id: 16,
    title: "Customer Support Executive",
    company: "Genpact",
    location: "Hyderabad",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Email Support","CRM","Data Entry","Communication"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-09",
    logo: "/logos/Genpact.png"
  },

  {
    id: 17,
    title: "Customer Support Executive",
    company: "IBM India",
    location: "Pune",
    salary: "4-7 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["CRM","Technical Support","Communication","Troubleshooting"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-08",
    logo: "/logos/IBM.png"
  },

  {
    id: 18,
    title: "Customer Support Executive",
    company: "Zoho",
    location: "Chennai",
    salary: "4-7 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Email Support","CRM","Product Support","Communication"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-08",
    logo: "/logos/Zoho.png"
  },

  {
    id: 19,
    title: "Customer Support Executive",
    company: "Freshworks",
    location: "Chennai",
    salary: "4-8 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Chat Support","CRM","Customer Success","Communication"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-07",
    logo: "/logos/Freshworks.jpg"
  },

  {
    id: 20,
    title: "Customer Support Executive",
    company: "Dell",
    location: "Bengaluru",
    salary: "4-8 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Technical Support","CRM","Hardware Support","Communication"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-07",
    logo: "/logos/Dell.png"
  },

  {
    id: 21,
    title: "Data Analyst",
    company: "Tata Consultancy Services",
    location: "Hyderabad",
    salary: "4-8 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["SQL","Excel","Python","Power BI","Communication"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-16",
    logo: "/logos/TCS.jpg"
  },

  {
    id: 22,
    title: "Data Analyst",
    company: "Infosys",
    location: "Bengaluru",
    salary: "5-9 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["SQL","Python","Tableau","Excel"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-16",
    logo: "/logos/Infosys.png"
  },

  {
    id: 23,
    title: "Data Analyst",
    company: "Wipro",
    location: "Pune",
    salary: "4-7 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["SQL","Excel","Power BI","Statistics"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-15",
    logo: "/logos/Wipro.png"
  },

  {
    id: 24,
    title: "Data Analyst",
    company: "HCL Technologies",
    location: "Chennai",
    salary: "5-10 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["SQL","Python","Power BI","Data Cleaning"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-15",
    logo: "/logos/HCL.png"
  },

  {
    id: 25,
    title: "Data Analyst",
    company: "Tech Mahindra",
    location: "Noida",
    salary: "4-8 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["SQL","Excel","Python","Data Visualization"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-14",
    logo: "/logos/TechMahindra.png"
  },

  {
    id: 26,
    title: "Data Analyst",
    company: "Capgemini",
    location: "Mumbai",
    salary: "5-9 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["SQL","Python","Tableau","Power BI"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-14",
    logo: "/logos/Capgemini.png"
  },

  {
    id: 27,
    title: "Data Analyst",
    company: "Cognizant",
    location: "Kolkata",
    salary: "4-8 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["SQL","Excel","Python","Data Analysis"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-13",
    logo: "/logos/Cognizant.jpg"
  },

  {
    id: 28,
    title: "Data Analyst",
    company: "Accenture",
    location: "Gurgaon",
    salary: "6-12 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["SQL","Python","Power BI","Azure"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-13",
    logo: "/logos/Accenture.png"
  },

  {
    id: 29,
    title: "Data Analyst",
    company: "IBM India",
    location: "Hyderabad",
    salary: "7-14 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["SQL","Python","Machine Learning","Tableau"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-12",
    logo: "/logos/IBM.png"
  },

  {
    id: 30,
    title: "Data Analyst",
    company: "Amazon India",
    location: "Bengaluru",
    salary: "10-18 LPA",
    experience: "3-7 Years",
    type: "Full Time",
    skills: ["SQL","Python","AWS","Data Warehousing"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-12",
    logo: "/logos/Amazon.png"
  },

  {
    id: 31,
    title: "Data Analyst",
    company: "Zoho",
    location: "Chennai",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["SQL","Excel","Python","BI Tools"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-11",
    logo: "/logos/Zoho.png"
  },

  {
    id: 32,
    title: "Data Analyst",
    company: "Mindtree",
    location: "Bengaluru",
    salary: "4-8 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["SQL","Python","Tableau","Excel"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-11",
    logo: "/logos/Mindtree.png"
  },

  {
    id: 33,
    title: "Data Analyst",
    company: "LTIMindtree",
    location: "Pune",
    salary: "5-10 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["SQL","Python","Power BI","ETL"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-10",
    logo: "/logos/Itimindtree.png"
  },

  {
    id: 34,
    title: "Data Analyst",
    company: "Oracle India",
    location: "Hyderabad",
    salary: "8-15 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["SQL","Python","Oracle DB","Analytics"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-10",
    logo: "/logos/Oracle.png"
  },

  {
    id: 35,
    title: "Data Analyst",
    company: "Paytm",
    location: "Noida",
    salary: "6-11 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["SQL","Python","Power BI","Fraud Analytics"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-09",
    logo: "/logos/Paytm.png"
  },

  {
    id: 36,
    title: "Data Analyst",
    company: "PhonePe",
    location: "Bengaluru",
    salary: "7-13 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["SQL","Python","Kafka","Data Pipelines"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-09",
    logo: "/logos/Phonepe.png"
  },

  {
    id: 37,
    title: "Data Analyst",
    company: "Flipkart",
    location: "Bengaluru",
    salary: "9-16 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["SQL","Python","Big Data","Spark"],
    status: "close",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-08",
    logo: "/logos/Flipkart.jpg"
  },

  {
    id: 38,
    title: "Data Analyst",
    company: "Zensar Technologies",
    location: "Pune",
    salary: "4-8 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["SQL","Excel","Power BI","Python"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-08",
    logo: "/logos/ZensarTechnologies.jpg"
  },

  {
    id: 39,
    title: "Data Analyst",
    company: "Persistent Systems",
    location: "Nagpur",
    salary: "5-9 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["SQL","Python","Tableau","Data Modeling"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-07",
    logo: "/logos/PWS.png"
  },

  {
    id: 40,
    title: "Data Analyst",
    company: "Mphasis",
    location: "Bengaluru",
    salary: "4-8 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["SQL","Excel","Python","Power BI"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-07",
    logo: "/logos/Mphasis.png"
  },

  {
    id: 41,
    title: "DevOps Engineer",
    company: "Google",
    location: "Bengaluru",
    salary: "18-35 LPA",
    experience: "3-7 Years",
    type: "Full Time",
    skills: ["GCP","Kubernetes","Docker","CI/CD"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-16",
    logo: "/logos/Google.png"
  },

  {
    id: 42,
    title: "DevOps Engineer",
    company: "Amazon",
    location: "Hyderabad",
    salary: "16-32 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["AWS","Terraform","Kubernetes","Linux"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-16",
    logo: "/logos/Amazon.png"
  },

  {
    id: 43,
    title: "DevOps Engineer",
    company: "Microsoft",
    location: "Hyderabad",
    salary: "18-34 LPA",
    experience: "3-7 Years",
    type: "Full Time",
    skills: ["Azure","DevOps","CI/CD","Docker"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-15",
    logo: "/logos/Microsoft.png"
  },

  {
    id: 44,
    title: "DevOps Engineer",
    company: "Meta",
    location: "Bengaluru",
    salary: "20-40 LPA",
    experience: "4-8 Years",
    type: "Full Time",
    skills: ["Linux","Kubernetes","CI/CD","Distributed Systems"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-15",
    logo: "/logos/Meta.png"
  },

  {
    id: 45,
    title: "DevOps Engineer",
    company: "Apple",
    location: "Hyderabad",
    salary: "22-45 LPA",
    experience: "4-8 Years",
    type: "Full Time",
    skills: ["Cloud Infra","CI/CD","Linux","Automation"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-14",
    logo: "/logos/Apple.png"
  },

  {
    id: 46,
    title: "DevOps Engineer",
    company: "Netflix",
    location: "Bengaluru",
    salary: "25-50 LPA",
    experience: "5-9 Years",
    type: "Full Time",
    skills: ["AWS","Microservices","CI/CD","Scaling Systems"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-14",
    logo: "/logos/Netflix.png"
  },

  {
    id: 47,
    title: "DevOps Engineer",
    company: "Oracle",
    location: "Bengaluru",
    salary: "15-28 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["OCI","Docker","Kubernetes","Terraform"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-13",
    logo: "/logos/Oracle.png"
  },

  {
    id: 48,
    title: "DevOps Engineer",
    company: "IBM",
    location: "Pune",
    salary: "14-26 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["Cloud","OpenShift","CI/CD","Linux"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-13",
    logo: "/logos/IBM.png"
  },

  {
    id: 49,
    title: "DevOps Engineer",
    company: "Accenture",
    location: "Gurgaon",
    salary: "10-20 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["AWS","DevOps","Jenkins","Docker"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-12",
    logo: "/logos/Accenture.png"
  },

  {
    id: 50,
    title: "DevOps Engineer",
    company: "Tata Consultancy Services",
    location: "Hyderabad",
    salary: "6-12 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Linux","CI/CD","Docker","AWS Basics"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-12",
    logo: "/logos/TCS.jpg"
  },

  {
    id: 51,
    title: "DevOps Engineer",
    company: "Infosys",
    location: "Bengaluru",
    salary: "6-11 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["AWS","Jenkins","Docker","Git"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-11",
    logo: "/logos/Infosys.png"
  },

  {
    id: 52,
    title: "DevOps Engineer",
    company: "Wipro",
    location: "Chennai",
    salary: "5-10 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Linux","Shell Scripting","CI/CD","Docker"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-11",
    logo: "/logos/Wipro.png"
  },

  {
    id: 53,
    title: "DevOps Engineer",
    company: "HCL Technologies",
    location: "Noida",
    salary: "8-15 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Kubernetes","AWS","Terraform","CI/CD"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-10",
    logo: "/logos/HCL.png"
  },

  {
    id: 54,
    title: "DevOps Engineer",
    company: "Tech Mahindra",
    location: "Pune",
    salary: "7-13 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["Docker","Jenkins","AWS","Linux"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-10",
    logo: "/logos/TechMahindra.png"
  },

  {
    id: 55,
    title: "DevOps Engineer",
    company: "Paytm",
    location: "Noida",
    salary: "12-22 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["AWS","Kubernetes","Microservices","CI/CD"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-09",
    logo: "/logos/Paytm.png"
  },

  {
    id: 56,
    title: "DevOps Engineer",
    company: "PhonePe",
    location: "Bengaluru",
    salary: "14-25 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["AWS","Kubernetes","Terraform","Observability"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-09",
    logo: "/logos/Phonepe.png"
  },

  {
    id: 57,
    title: "DevOps Engineer",
    company: "Flipkart",
    location: "Bengaluru",
    salary: "18-30 LPA",
    experience: "4-7 Years",
    type: "Full Time",
    skills: ["AWS","Kubernetes","CI/CD","Scaling Systems"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-08",
    logo: "/logos/Flipkart.jpg"
  },

  {
    id: 58,
    title: "DevOps Engineer",
    company: "Zoho",
    location: "Chennai",
    salary: "10-18 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Linux","Docker","CI/CD","Scripting"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-08",
    logo: "/logos/Zoho.png"
  },

  {
    id: 59,
    title: "DevOps Engineer",
    company: "Persistent Systems",
    location: "Nagpur",
    salary: "9-16 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["AWS","Docker","Jenkins","Terraform"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-07",
    logo: "/logos/PWS.png"
  },

  {
    id: 60,
    title: "DevOps Engineer",
    company: "Capgemini",
    location: "Mumbai",
    salary: "8-14 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["Linux","Docker","CI/CD","AWS"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-07",
    logo: "/logos/Capgemini.png"
  },

  {
    id: 61,
    title: "Digital Marketing Specialist",
    company: "Google India",
    location: "Bengaluru",
    salary: "15-30 LPA",
    experience: "2-6 Years",
    type: "Full Time",
    skills: ["SEO","Google Ads","Analytics","Content Marketing"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-16",
    logo: "/logos/Google.png"
  },

  {
    id: 62,
    title: "Digital Marketing Specialist",
    company: "Amazon India",
    location: "Hyderabad",
    salary: "12-25 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["SEO","PPC","Marketing Strategy","Data Analytics"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-16",
    logo: "/logos/Amazon.png"
  },

  {
    id: 63,
    title: "Digital Marketing Specialist",
    company: "Flipkart",
    location: "Bengaluru",
    salary: "10-20 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["SEO","SEM","Google Ads","Social Media"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-15",
    logo: "/logos/Flipkart.jpg"
  },

  {
    id: 64,
    title: "Digital Marketing Specialist",
    company: "Meta",
    location: "Gurgaon",
    salary: "18-35 LPA",
    experience: "3-7 Years",
    type: "Full Time",
    skills: ["Facebook Ads","Instagram Ads","Growth Marketing","Analytics"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-15",
    logo: "/logos/Meta.png"
  },

  {
    id: 65,
    title: "Digital Marketing Specialist",
    company: "Adobe",
    location: "Noida",
    salary: "15-28 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["SEO","Content Strategy","Analytics","Adobe Tools"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-14",
    logo: "/logos/Adobe.png"
  },

  {
    id: 66,
    title: "Digital Marketing Specialist",
    company: "Zoho",
    location: "Chennai",
    salary: "6-12 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["SEO","Content Marketing","Email Marketing","Analytics"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-14",
    logo: "/logos/Zoho.png"
  },

  {
    id: 67,
    title: "Digital Marketing Specialist",
    company: "Freshworks",
    location: "Chennai",
    salary: "8-15 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["SaaS Marketing","SEO","PPC","Growth Marketing"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-13",
    logo: "/logos/Freshworks.jpg"
  },

  {
    id: 68,
    title: "Digital Marketing Specialist",
    company: "Paytm",
    location: "Noida",
    salary: "8-16 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["SEO","SEM","Performance Marketing","Analytics"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-13",
    logo: "/logos/Paytm.png"
  },

  {
    id: 69,
    title: "Digital Marketing Specialist",
    company: "Swiggy",
    location: "Bengaluru",
    salary: "8-14 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["Growth Marketing","SEO","Social Media","Branding"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-12",
    logo: "/logos/Swiggy.png"
  },

  {
    id: 70,
    title: "Digital Marketing Specialist",
    company: "Zomato",
    location: "Gurgaon",
    salary: "8-14 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["SEO","Content Marketing","Social Media","Analytics"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-12",
    logo: "/logos/Zomato.png"
  },

  {
    id: 71,
    title: "Digital Marketing Specialist",
    company: "Tata Consultancy Services",
    location: "Hyderabad",
    salary: "5-10 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["SEO","Google Ads","Reporting","Marketing Tools"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-11",
    logo: "/logos/TCS.jpg"
  },

  {
    id: 72,
    title: "Digital Marketing Specialist",
    company: "Infosys",
    location: "Bengaluru",
    salary: "6-11 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["SEO","Content Marketing","Analytics","PPC"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-11",
    logo: "/logos/Infosys.png"
  },

  {
    id: 73,
    title: "Digital Marketing Specialist",
    company: "Accenture",
    location: "Gurgaon",
    salary: "10-18 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Digital Strategy","SEO","Analytics","Branding"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-10",
    logo: "/logos/Accenture.png"
  },

  {
    id: 74,
    title: "Digital Marketing Specialist",
    company: "IBM India",
    location: "Pune",
    salary: "12-20 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["Marketing Automation","SEO","Analytics","AI Marketing"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-10",
    logo: "/logos/IBM.png"
  },

  {
    id: 75,
    title: "Digital Marketing Specialist",
    company: "Capgemini",
    location: "Mumbai",
    salary: "7-12 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["SEO","PPC","Content Strategy","Analytics"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-09",
    logo: "/logos/Capgemini.png"
  },

  {
    id: 76,
    title: "Digital Marketing Specialist",
    company: "HCL Technologies",
    location: "Noida",
    salary: "6-11 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["SEO","Email Marketing","Analytics","Content"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-09",
    logo: "/logos/HCL.png"
  },

  {
    id: 77,
    title: "Digital Marketing Specialist",
    company: "Adobe",
    location: "Bengaluru",
    salary: "15-28 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["SEO","Adobe Analytics","Content Strategy","UX Marketing"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-08",
    logo: "/logos/Adobe.png"
  },

  {
    id: 78,
    title: "Digital Marketing Specialist",
    company: "Oracle",
    location: "Hyderabad",
    salary: "14-25 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["SEO","Marketing Cloud","Analytics","Automation"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-08",
    logo: "/logos/Oracle.png"
  },

  {
    id: 79,
    title: "Digital Marketing Specialist",
    company: "LinkedIn India",
    location: "Bengaluru",
    salary: "18-30 LPA",
    experience: "3-7 Years",
    type: "Full Time",
    skills: ["LinkedIn Ads","B2B Marketing","SEO","Analytics"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-07",
    logo: "/logos/LinkedIn.png"
  },

  {
    id: 80,
    title: "Digital Marketing Specialist",
    company: "Microsoft India",
    location: "Hyderabad",
    salary: "18-35 LPA",
    experience: "3-7 Years",
    type: "Full Time",
    skills: ["SEO","Azure Marketing","Analytics","Growth Strategy"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-07",
    logo: "/logos/Microsoft.png"
  },

  {
    id: 81,
    title: "Financial Analyst",
    company: "Goldman Sachs",
    location: "Bengaluru",
    salary: "12-25 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Financial Modeling","Excel","Valuation","SQL"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2 days ago",
    logo: "/logos/GoldmanSachs.png"
  },

  {
    id: 82,
    title: "Financial Analyst",
    company: "JP Morgan Chase",
    location: "Mumbai",
    salary: "10-22 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Excel","Financial Modeling","Risk Analysis","SQL"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "1 day ago",
    logo: "/logos/JPMorganChase.png"
  },

  {
    id: 83,
    title: "Financial Analyst",
    company: "Morgan Stanley",
    location: "Mumbai",
    salary: "12-24 LPA",
    experience: "2-6 Years",
    type: "Full Time",
    skills: ["Valuation","Excel","Equity Research","Power BI"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "3 days ago",
    logo: "/logos/Morganstanley.png"
  },

  {
    id: 84,
    title: "Financial Analyst",
    company: "HDFC Bank",
    location: "Mumbai",
    salary: "6-12 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Excel","Accounting","Risk Analysis","Financial Reporting"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "5 days ago",
    logo: "/logos/HDFC.jpg"
  },

  {
    id: 85,
    title: "Financial Analyst",
    company: "ICICI Bank",
    location: "Hyderabad",
    salary: "6-11 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Excel","Financial Planning","SQL","Reporting"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2 days ago",
    logo: "/logos/ICICI.jpg"
  },

  {
    id: 86,
    title: "Financial Analyst",
    company: "Axis Bank",
    location: "Bengaluru",
    salary: "5-10 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Excel","Financial Analysis","Risk Management","SQL"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "1 week ago",
    logo: "/logos/Axis Bank.jpg"
  },

  {
    id: 87,
    title: "Financial Analyst",
    company: "Deloitte",
    location: "Gurgaon",
    salary: "8-18 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Valuation","Excel","Audit","Financial Modeling"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "4 days ago",
    logo: "/logos/Deloitte.png"
  },

  {
    id: 88,
    title: "Financial Analyst",
    company: "PwC India",
    location: "Mumbai",
    salary: "8-16 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Excel","Risk Analysis","Taxation","Reporting"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2 days ago",
    logo: "/logos/PWS.png"
  },

  {
    id: 89,
    title: "Financial Analyst",
    company: "EY India",
    location: "Bengaluru",
    salary: "8-15 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Financial Modeling","Excel","Audit","Analytics"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "3 days ago",
    logo: "/logos/EY.png"
  },

  {
    id: 90,
    title: "Financial Analyst",
    company: "KPMG",
    location: "Gurgaon",
    salary: "9-17 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Excel","Valuation","Risk Analysis","Compliance"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "1 day ago",
    logo: "/logos/KPMG.png"
  },

  {
    id: 91,
    title: "Financial Analyst",
    company: "Paytm",
    location: "Noida",
    salary: "7-14 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["Excel","Financial Reporting","SQL","Data Analysis"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "5 days ago",
    logo: "/logos/Paytm.png"
  },

  {
    id: 92,
    title: "Financial Analyst",
    company: "Flipkart",
    location: "Bengaluru",
    salary: "10-18 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Financial Modeling","Excel","Forecasting","SQL"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2 days ago",
    logo: "/logos/Flipkart.jpg"
  },

  {
    id: 93,
    title: "Financial Analyst",
    company: "Amazon India",
    location: "Hyderabad",
    salary: "12-22 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["Excel","Data Analysis","SQL","Forecasting"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "Today",
    logo: "/logos/Amazon.png"
  },

  {
    id: 94,
    title: "Financial Analyst",
    company: "Infosys",
    location: "Bengaluru",
    salary: "6-11 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Excel","SQL","Reporting","Analytics"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "3 days ago",
    logo: "/logos/Infosys.png"
  },

  {
    id: 95,
    title: "Financial Analyst",
    company: "TCS",
    location: "Chennai",
    salary: "5-10 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Excel","Financial Reporting","SQL","Accounting"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "4 days ago",
    logo: "/logos/TCS.jpg"
  },

  {
    id: 96,
    title: "Financial Analyst",
    company: "Wipro",
    location: "Pune",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Excel","Accounting","Reporting","SQL"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "1 week ago",
    logo: "/logos/Wipro.png"
  },

  {
    id: 97,
    title: "Financial Analyst",
    company: "HCL Technologies",
    location: "Noida",
    salary: "6-12 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["Excel","Financial Analysis","SQL","Forecasting"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2 days ago",
    logo: "/logos/HCL.png"
  },

  {
    id: 98,
    title: "Financial Analyst",
    company: "Capgemini",
    location: "Mumbai",
    salary: "6-11 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Excel","Financial Modeling","SQL","Analytics"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "6 days ago",
    logo: "/logos/Capgemini.png"
  },

  {
    id: 99,
    title: "Financial Analyst",
    company: "Accenture",
    location: "Gurgaon",
    salary: "8-15 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Excel","Valuation","Risk Analysis","Power BI"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "Today",
    logo: "../logos/Accenture.png"
  },

  {
    id: 101,
    title: "HR Executive",
    company: "Tata Consultancy Services",
    location: "Hyderabad",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Recruitment","HR Operations","MS Excel","Communication"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-16",
    logo: "/logos/TCS.jpg"
  },

  {
    id: 102,
    title: "HR Executive",
    company: "Infosys",
    location: "Bengaluru",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Talent Acquisition","HR Policies","Excel","Communication"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-16",
    logo: "/logos/Infosys.png"
  },

  {
    id: 103,
    title: "HR Executive",
    company: "Wipro",
    location: "Chennai",
    salary: "3-5 LPA",
    experience: "0-2 Years",
    type: "Full Time",
    skills: ["Recruitment","HR Operations","Communication","Onboarding"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-15",
    logo: "/logos/Wipro.png"
  },

  {
    id: 104,
    title: "HR Executive",
    company: "HCL Technologies",
    location: "Noida",
    salary: "4-7 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Recruitment","Employee Engagement","HRMS","Communication"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-15",
    logo: "/logos/HCL.png"
  },

  {
    id: 105,
    title: "HR Executive",
    company: "Accenture",
    location: "Gurgaon",
    salary: "5-9 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Talent Acquisition","HR Analytics","Communication","Excel"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-14",
    logo: "/logos/Accenture.png"
  },

  {
    id: 106,
    title: "HR Executive",
    company: "Capgemini",
    location: "Mumbai",
    salary: "4-7 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Recruitment","HR Operations","Interviewing","Communication"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-14",
    logo: "/logos/Capgemini.png"
  },

  {
    id: 107,
    title: "HR Executive",
    company: "Tech Mahindra",
    location: "Pune",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Recruitment","HRMS","Communication","Onboarding"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-13",
    logo: "/logos/TechMahindra.png"
  },

  {
    id: 108,
    title: "HR Executive",
    company: "Genpact",
    location: "Hyderabad",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["HR Operations","Recruitment","Excel","Communication"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-13",
    logo: "/logos/Genpact.png"
  },

  {
    id: 109,
    title: "HR Executive",
    company: "IBM India",
    location: "Bengaluru",
    salary: "5-8 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["HR Analytics","Recruitment","Employee Relations","HRMS"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-12",
    logo: "/logos/IBM.png"
  },

  {
    id: 110,
    title: "HR Executive",
    company: "Amazon India",
    location: "Hyderabad",
    salary: "6-10 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Recruitment","HR Operations","Communication","Data Handling"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-12",
    logo: "/logos/Amazon.png"
  },

  {
    id: 111,
    title: "HR Executive",
    company: "Flipkart",
    location: "Bengaluru",
    salary: "6-10 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Talent Acquisition","HR Operations","Interviewing","Excel"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-11",
    logo: "/logos/Flipkart.jpg"
  },

  {
    id: 112,
    title: "HR Executive",
    company: "Zoho",
    location: "Chennai",
    salary: "4-8 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Recruitment","HR Policies","Communication","HRMS"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-11",
    logo: "/logos/Zoho.png"
  },

  {
    id: 113,
    title: "HR Executive",
    company: "Paytm",
    location: "Noida",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Recruitment","Employee Engagement","Communication","Excel"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-10",
    logo: "/logos/Paytm.png"
  },

  {
    id: 114,
    title: "HR Executive",
    company: "HDFC Bank",
    location: "Mumbai",
    salary: "4-7 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Recruitment","HR Operations","Communication","HRMS"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-10",
    logo: "/logos/HDFC.jpg"
  },

  {
    id: 115,
    title: "HR Executive",
    company: "ICICI Bank",
    location: "Hyderabad",
    salary: "4-7 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Recruitment","Onboarding","HR Policies","Communication"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-09",
    logo: "/logos/ICICI.jpg"
  },

  {
    id: 116,
    title: "HR Executive",
    company: "Axis Bank",
    location: "Bengaluru",
    salary: "4-6 LPA",
    experience: "0-2 Years",
    type: "Full Time",
    skills: ["Recruitment","HRMS","Communication","Excel"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-09",
    logo: "/logos/Axis Bank.jpg"
  },

  {
    id: 117,
    title: "HR Executive",
    company: "Cognizant",
    location: "Kolkata",
    salary: "4-7 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["HR Operations","Recruitment","Excel","Communication"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-08",
    logo: "/logos/Cognizant.jpg"
  },

  {
    id: 118,
    title: "HR Executive",
    company: "L&T Infotech",
    location: "Mumbai",
    salary: "5-8 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Talent Acquisition","HR Analytics","Communication","HRMS"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-08",
    logo: "/logos/Itimindtree.png"
  },

  {
    id: 119,
    title: "HR Executive",
    company: "Deloitte",
    location: "Gurgaon",
    salary: "6-10 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Recruitment","HR Strategy","Communication","Excel"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-07",
    logo: "/logos/Deloitte.png"
  },

  {
    id: 120,
    title: "HR Executive",
    company: "KPMG India",
    location: "Mumbai",
    salary: "6-10 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Talent Acquisition","HR Analytics","Communication","Compliance"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-07",
    logo: "/logos/KPMG.png"
  },

  {
    id: 121,
    title: "Java Developer",
    company: "Tata Consultancy Services",
    location: "Hyderabad",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","SQL","REST API"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2 days ago",
    logo: "/logos/TCS.jpg"
  },

  {
    id: 122,
    title: "Java Developer",
    company: "Infosys",
    location: "Bengaluru",
    salary: "6-10 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Java","Spring MVC","MySQL","Git"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "Today",
    logo: "/logos/Infosys.png"
  },

  {
    id: 123,
    title: "Java Developer",
    company: "Wipro",
    location: "Pune",
    salary: "4-8 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Java","OOPs","SQL","HTML"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "6 days ago",
    logo: "/logos/Wipro.png"
  },

  {
    id: 124,
    title: "Java Developer",
    company: "HCL Technologies",
    location: "Chennai",
    salary: "6-11 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","Microservices","Docker"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "1 day ago",
    logo: "/logos/HCL.png"
  },

  {
    id: 125,
    title: "Java Developer",
    company: "Tech Mahindra",
    location: "Noida",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Java","REST API","Spring Boot","SQL"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "4 days ago",
    logo: "/logos/TechMahindra.png"
  },

  {
    id: 126,
    title: "Java Developer",
    company: "Capgemini",
    location: "Mumbai",
    salary: "6-10 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","Hibernate","SQL"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2 days ago",
    logo: "/logos/Capgemini.png"
  },

  {
    id: 127,
    title: "Java Developer",
    company: "Cognizant",
    location: "Kolkata",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","REST API","SQL"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "1 week ago",
    logo: "/logos/Cognizant.jpg"
  },

  {
    id: 128,
    title: "Java Developer",
    company: "Accenture",
    location: "Gurgaon",
    salary: "7-13 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Java","Microservices","AWS","Spring Boot"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "Today",
    logo: "../logos/Accenture.png"
  },

  {
    id: 129,
    title: "Java Developer",
    company: "IBM India",
    location: "Hyderabad",
    salary: "8-14 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["Java","Cloud","Microservices","Kubernetes"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "1 day ago",
    logo: "/logos/IBM.png"
  },

  {
    id: 130,
    title: "Java Developer",
    company: "Amazon India",
    location: "Bengaluru",
    salary: "12-22 LPA",
    experience: "3-7 Years",
    type: "Full Time",
    skills: ["Java","System Design","Microservices","AWS"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "Today",
    logo: "/logos/Amazon.png"
  },

  {
    id: 131,
    title: "Java Developer",
    company: "Mindtree",
    location: "Bengaluru",
    salary: "5-9 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","React","SQL"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "5 days ago",
    logo: "/logos/Mindtree.png"
  },

  {
    id: 132,
    title: "Java Developer",
    company: "LTIMindtree",
    location: "Pune",
    salary: "6-11 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","Microservices","MongoDB"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "3 days ago",
    logo: "/logos/Itimindtree.png"
  },

  {
    id: 133,
    title: "Java Developer",
    company: "Oracle India",
    location: "Hyderabad",
    salary: "10-18 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["Java","Cloud","Database","Microservices"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2 days ago",
    logo: "/logos/Oracle.png"
  },

  {
    id: 134,
    title: "Java Developer",
    company: "Paytm",
    location: "Noida",
    salary: "7-12 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","Redis","Microservices"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "4 days ago",
    logo: "/logos/Paytm.png"
  },

  {
    id: 135,
    title: "Java Developer",
    company: "PhonePe",
    location: "Bengaluru",
    salary: "8-15 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Java","Kafka","Microservices","System Design"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "Today",
    logo: "/logos/Phonepe.png"
  },

  {
    id: 136,
    title: "Java Developer",
    company: "Flipkart",
    location: "Bengaluru",
    salary: "10-18 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["Java","System Design","Kafka","Microservices"],
    status: "close",
    featured: true,
    topCompany: true,
    postedOn: "3 days ago",
    logo: "/logos/Flipkart.jpg"
  },

  {
    id: 137,
    title: "Java Developer",
    company: "Zensar Technologies",
    location: "Pune",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","SQL","HTML"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "6 days ago",
    logo: "/logos/ZensarTechnologies.jpg"
  },

  {
    id: 138,
    title: "Java Developer",
    company: "Mphasis",
    location: "Bengaluru",
    salary: "5-8 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","SQL","Git"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "1 week ago",
    logo: "/logos/Mphasis.png"
  },

  {
    id: 141,
    title: "Java Full Stack Developer",
    company: "Tata Consultancy Services",
    location: "Hyderabad",
    salary: "6-10 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","React","SQL"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-16",
    logo: "/logos/TCS.jpg"
  },

  {
    id: 142,
    title: "Java Full Stack Developer",
    company: "Infosys",
    location: "Bengaluru",
    salary: "5-9 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","Angular","MySQL"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-16",
    logo: "/logos/Infosys.png"
  },

  {
    id: 143,
    title: "Java Full Stack Developer",
    company: "Wipro",
    location: "Pune",
    salary: "4-8 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Java","Spring MVC","React","MongoDB"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-15",
    logo: "/logos/Wipro.png"
  },

  {
    id: 144,
    title: "Java Full Stack Developer",
    company: "HCL Technologies",
    location: "Chennai",
    salary: "6-12 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","Vue.js","PostgreSQL"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-15",
    logo: "/logos/HCL.png"
  },

  {
    id: 145,
    title: "Java Full Stack Developer",
    company: "Tech Mahindra",
    location: "Noida",
    salary: "5-10 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","React","Docker"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-14",
    logo: "/logos/TechMahindra.png"
  },

  {
    id: 146,
    title: "Java Full Stack Developer",
    company: "Capgemini",
    location: "Mumbai",
    salary: "6-11 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","Angular","Oracle"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-14",
    logo: "/logos/Capgemini.png"
  },

  {
    id: 147,
    title: "Java Full Stack Developer",
    company: "Cognizant",
    location: "Kolkata",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","React","MySQL"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-13",
    logo: "/logos/Cognizant.jpg"
  },

  {
    id: 148,
    title: "Java Full Stack Developer",
    company: "Accenture",
    location: "Gurgaon",
    salary: "7-13 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","React","AWS"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-13",
    logo: "/logos/Accenture.png"
  },

  {
    id: 149,
    title: "Java Full Stack Developer",
    company: "IBM India",
    location: "Hyderabad",
    salary: "8-14 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","Microservices","Kubernetes"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-12",
    logo: "/logos/IBM.png"
  },

  {
    id: 150,
    title: "Java Full Stack Developer",
    company: "Amazon India",
    location: "Bengaluru",
    salary: "12-20 LPA",
    experience: "3-7 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","React","AWS"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-12",
    logo: "/logos/Amazon.png"
  },

  {
    id: 151,
    title: "Java Full Stack Developer",
    company: "Zoho",
    location: "Chennai",
    salary: "6-10 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","React","MySQL"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-11",
    logo: "/logos/Zoho.png"
  },

  {
    id: 152,
    title: "Java Full Stack Developer",
    company: "Mindtree",
    location: "Bengaluru",
    salary: "5-9 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","Angular","SQL"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-11",
    logo: "/logos/Mindtree.png"
  },

  {
    id: 153,
    title: "Java Full Stack Developer",
    company: "LTIMindtree",
    location: "Pune",
    salary: "6-11 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","React","MongoDB"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-10",
    logo: "/logos/Itimindtree.png"
  },

  {
    id: 154,
    title: "Java Full Stack Developer",
    company: "Oracle India",
    location: "Hyderabad",
    salary: "10-18 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","Microservices","SQL"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-10",
    logo: "/logos/Oracle.png"
  },

  {
    id: 155,
    title: "Java Full Stack Developer",
    company: "Paytm",
    location: "Noida",
    salary: "7-12 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","React","Redis"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-09",
    logo: "/logos/Paytm.png"
  },

  {
    id: 156,
    title: "Java Full Stack Developer",
    company: "PhonePe",
    location: "Bengaluru",
    salary: "8-15 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","Kafka","Microservices"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-09",
    logo: "/logos/Phonepe.png"
  },

  {
    id: 157,
    title: "Java Full Stack Developer",
    company: "Flipkart",
    location: "Bengaluru",
    salary: "10-18 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","React","Kafka"],
    status: "close",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-08",
    logo: "/logos/Flipkart.jpg"
  },

  {
    id: 158,
    title: "Java Full Stack Developer",
    company: "Zensar Technologies",
    location: "Pune",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","Angular","SQL"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-08",
    logo: "/logos/ZensarTechnologies.jpg"
  },

  {
    id: 159,
    title: "Java Full Stack Developer",
    company: "Persistent Systems",
    location: "Nagpur",
    salary: "6-10 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","React","PostgreSQL"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-07",
    logo: "/logos/PWS.png"
  },

  {
    id: 160,
    title: "Java Full Stack Developer",
    company: "Mphasis",
    location: "Bengaluru",
    salary: "5-8 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","React","MySQL"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-07",
    logo: "/logos/Mphasis.png"
  },

  {
    id: 161,
    title: "Python Developer",
    company: "Tata Consultancy Services",
    location: "Hyderabad",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Python","Django","REST API","SQL"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2 days ago",
    logo: "/logos/TCS.jpg"
  },

  {
    id: 162,
    title: "Python Developer",
    company: "Infosys",
    location: "Bengaluru",
    salary: "6-10 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Python","Flask","MySQL","Git"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "Today",
    logo: "/logos/Infosys.png"
  },

  {
    id: 163,
    title: "Python Developer",
    company: "Wipro",
    location: "Pune",
    salary: "4-8 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Python","Django","HTML","CSS"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "6 days ago",
    logo: "/logos/Wipro.png"
  },

  {
    id: 164,
    title: "Python Developer",
    company: "HCL Technologies",
    location: "Chennai",
    salary: "6-11 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Python","FastAPI","PostgreSQL","Docker"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "1 day ago",
    logo: "/logos/HCL.png"
  },

  {
    id: 165,
    title: "Python Developer",
    company: "Tech Mahindra",
    location: "Noida",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Python","Django","REST API","MongoDB"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "4 days ago",
    logo: "/logos/TechMahindra.png"
  },

  {
    id: 166,
    title: "Python Developer",
    company: "Capgemini",
    location: "Mumbai",
    salary: "6-10 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["Python","Flask","SQL","AWS"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2 days ago",
    logo: "/logos/Capgemini.png"
  },

  {
    id: 167,
    title: "Python Developer",
    company: "Cognizant",
    location: "Kolkata",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Python","Django","REST API","JavaScript"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "1 week ago",
    logo: "/logos/Cognizant.jpg"
  },

  {
    id: 168,
    title: "Python Developer",
    company: "Accenture",
    location: "Gurgaon",
    salary: "7-12 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Python","Microservices","AWS","SQL"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "Today",
    logo: "../logos/Accenture.png"
  },

  {
    id: 169,
    title: "Python Developer",
    company: "IBM India",
    location: "Hyderabad",
    salary: "8-14 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["Python","AI/ML","Cloud","Docker"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "1 day ago",
    logo: "/logos/IBM.png"
  },

  {
    id: 170,
    title: "Python Developer",
    company: "Amazon India",
    location: "Bengaluru",
    salary: "12-22 LPA",
    experience: "3-7 Years",
    type: "Full Time",
    skills: ["Python","AWS","Microservices","Lambda"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "Today",
    logo: "/logos/Amazon.png"
  },

  {
    id: 171,
    title: "Python Developer",
    company: "Mindtree",
    location: "Bengaluru",
    salary: "5-9 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Python","Flask","JavaScript","SQL"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "5 days ago",
    logo: "/logos/Mindtree.png"
  },

  {
    id: 172,
    title: "Python Developer",
    company: "LTIMindtree",
    location: "Pune",
    salary: "6-11 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Python","Django","Microservices","PostgreSQL"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "3 days ago",
    logo: "/logos/Itimindtree.png"
  },

  {
    id: 173,
    title: "Python Developer",
    company: "Oracle India",
    location: "Hyderabad",
    salary: "10-18 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["Python","Cloud","SQL","APIs"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2 days ago",
    logo: "/logos/Oracle.png"
  },

  {
    id: 174,
    title: "Python Developer",
    company: "Paytm",
    location: "Noida",
    salary: "7-12 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["Python","Django","Redis","REST API"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "4 days ago",
    logo: "/logos/Paytm.png"
  },

  {
    id: 175,
    title: "Python Developer",
    company: "PhonePe",
    location: "Bengaluru",
    salary: "8-15 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Python","FastAPI","Kafka","Microservices"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "Today",
    logo: "/logos/Phonepe.png"
  },

  {
    id: 176,
    title: "Python Developer",
    company: "Flipkart",
    location: "Bengaluru",
    salary: "10-18 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["Python","Django","Microservices","AWS"],
    status: "close",
    featured: true,
    topCompany: true,
    postedOn: "3 days ago",
    logo: "/logos/Flipkart.jpg"
  },

  {
    id: 177,
    title: "Python Developer",
    company: "Zensar Technologies",
    location: "Pune",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Python","Flask","SQL","Git"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "6 days ago",
    logo: "/logos/ZensarTechnologies.jpg"
  },

  {
    id: 178,
    title: "Python Developer",
    company: "Mphasis",
    location: "Bengaluru",
    salary: "5-8 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Python","Flask","HTML","CSS"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "1 week ago",
    logo: "/logos/Mphasis.png"
  },

  {
    id: 181,
    title: "Data Analyst",
    company: "Mu Sigma",
    location: "Bengaluru",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["SQL","Python","Excel","Power BI"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-16",
    logo: "/logos/Musigma.png"
  },

  {
    id: 182,
    title: "QA Engineer",
    company: "BrowserStack",
    location: "Mumbai",
    salary: "6-11 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Manual Testing","Selenium","API Testing","Java"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-16",
    logo: "/logos/Browserstack.png"
  },

  {
    id: 183,
    title: "Data Analyst",
    company: "Fractal Analytics",
    location: "Gurgaon",
    salary: "7-13 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Python","SQL","Machine Learning","Tableau"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-15",
    logo: "/logos/Fractal.png"
  },

  {
    id: 184,
    title: "QA Engineer",
    company: "Postman",
    location: "Bengaluru",
    salary: "8-15 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["API Testing","Automation","Postman","JavaScript"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-15",
    logo: "/logos/Postman.png"
  },

  {
    id: 185,
    title: "Data Analyst",
    company: "LatentView Analytics",
    location: "Chennai",
    salary: "5-10 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["SQL","Python","Excel","Power BI"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-14",
    logo: "/logos/Latentview.png"
  },

  {
    id: 186,
    title: "QA Engineer",
    company: "Freshworks",
    location: "Chennai",
    salary: "6-12 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Selenium","Manual Testing","Automation","API Testing"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-14",
    logo: "/logos/Freshworks.jpg"
  },

  {
    id: 187,
    title: "Data Analyst",
    company: "Tiger Analytics",
    location: "Bengaluru",
    salary: "6-12 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["Python","SQL","Power BI","Statistics"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-13",
    logo: "/logos/Tigeranalytics.png"
  },

  {
    id: 188,
    title: "QA Engineer",
    company: "Zoho",
    location: "Chennai",
    salary: "5-10 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Manual Testing","Selenium","Java","SQL"],
    status: "close",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-13",
    logo: "/logos/Zoho.png"
  },

  {
    id: 189,
    title: "Data Analyst",
    company: "Kantar",
    location: "Mumbai",
    salary: "4-8 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Excel","SQL","Data Visualization","Python"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-12",
    logo: "/logos/Kantar.png"
  },

  {
    id: 190,
    title: "QA Engineer",
    company: "ThoughtWorks",
    location: "Bengaluru",
    salary: "8-16 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Automation Testing","Selenium","CI/CD","Java"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-12",
    logo: "/logos/Thoughtworks.png"
  },

  {
    id: 191,
    title: "Data Analyst",
    company: "Cognizant",
    location: "Hyderabad",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["SQL","Python","Excel","Power BI"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-11",
    logo: "/logos/Cognizant.jpg"
  },

  {
    id: 192,
    title: "QA Engineer",
    company: "Accenture",
    location: "Gurgaon",
    salary: "6-12 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Selenium","API Testing","Java","Automation"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-11",
    logo: "/logos/Accenture.png"
  },

  {
    id: 193,
    title: "Data Analyst",
    company: "IBM India",
    location: "Pune",
    salary: "8-14 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["Python","SQL","AI/ML","Tableau"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-10",
    logo: "/logos/IBM.png"
  },

  {
    id: 194,
    title: "QA Engineer",
    company: "Microsoft India",
    location: "Hyderabad",
    salary: "12-25 LPA",
    experience: "3-7 Years",
    type: "Full Time",
    skills: ["Automation","Selenium","C#","Azure DevOps"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-10",
    logo: "/logos/Microsoft.png"
  },

  {
    id: 195,
    title: "Data Analyst",
    company: "Amazon India",
    location: "Bengaluru",
    salary: "10-20 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["SQL","Python","AWS","QuickSight"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-09",
    logo: "/logos/Amazon.png"
  },

  {
    id: 196,
    title: "QA Engineer",
    company: "Google India",
    location: "Bengaluru",
    salary: "15-30 LPA",
    experience: "3-7 Years",
    type: "Full Time",
    skills: ["Automation","Selenium","Python","System Testing"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-09",
    logo: "/logos/Google.png"
  },

  {
    id: 197,
    title: "Data Analyst",
    company: "Flipkart",
    location: "Bengaluru",
    salary: "10-18 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["SQL","Python","Big Data","Tableau"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-08",
    logo: "/logos/Flipkart.jpg"
  },

  {
    id: 198,
    title: "QA Engineer",
    company: "Paytm",
    location: "Noida",
    salary: "7-12 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["Manual Testing","Automation","API Testing","SQL"],
    status: "close",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-08",
    logo: "/logos/Paytm.png"
  },

  {
    id: 199,
    title: "Data Analyst",
    company: "Capgemini",
    location: "Mumbai",
    salary: "6-10 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["SQL","Excel","Power BI","Python"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-07",
    logo: "/logos/Capgemini.png"
  },

  {
    id: 200,
    title: "QA Engineer",
    company: "TCS Digital",
    location: "Chennai",
    salary: "6-11 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Selenium","Java","API Testing","Automation"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-07",
    logo: "/logos/TCS.jpg"
  },

  {
    id: 201,
    title: "React Developer",
    company: "Tata Consultancy Services",
    location: "Hyderabad",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["React","JavaScript","HTML","CSS"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2 days ago",
    logo: "/logos/TCS.jpg"
  },

  {
    id: 202,
    title: "React Developer",
    company: "Infosys",
    location: "Bengaluru",
    salary: "6-10 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["React","Redux","JavaScript","REST API"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "Today",
    logo: "/logos/Infosys.png"
  },

  {
    id: 203,
    title: "React Developer",
    company: "Wipro",
    location: "Pune",
    salary: "4-8 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["React","JavaScript","CSS","Bootstrap"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "6 days ago",
    logo: "/logos/Wipro.png"
  },

  {
    id: 204,
    title: "React Developer",
    company: "HCL Technologies",
    location: "Chennai",
    salary: "6-11 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["React","TypeScript","Redux","API Integration"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "1 day ago",
    logo: "/logos/HCL.png"
  },

  {
    id: 205,
    title: "React Developer",
    company: "Tech Mahindra",
    location: "Noida",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["React","JavaScript","Tailwind CSS","REST API"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "4 days ago",
    logo: "/logos/TechMahindra.png"
  },

  {
    id: 206,
    title: "React Developer",
    company: "Capgemini",
    location: "Mumbai",
    salary: "6-10 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["React","Redux","JavaScript","Git"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2 days ago",
    logo: "/logos/Capgemini.png"
  },

  {
    id: 207,
    title: "React Developer",
    company: "Cognizant",
    location: "Kolkata",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["React","JavaScript","HTML","CSS"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "1 week ago",
    logo: "/logos/Cognizant.jpg"
  },

  {
    id: 208,
    title: "React Developer",
    company: "Accenture",
    location: "Gurgaon",
    salary: "7-12 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["React","TypeScript","Redux","AWS"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "Today",
    logo: "../logos/Accenture.png"
  },

  {
    id: 209,
    title: "React Developer",
    company: "IBM India",
    location: "Hyderabad",
    salary: "8-14 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["React","Micro Frontend","JavaScript","Cloud"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "1 day ago",
    logo: "/logos/IBM.png"
  },

  {
    id: 210,
    title: "React Developer",
    company: "Amazon India",
    location: "Bengaluru",
    salary: "12-22 LPA",
    experience: "3-7 Years",
    type: "Full Time",
    skills: ["React","Next.js","TypeScript","AWS"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "Today",
    logo: "/logos/Amazon.png"
  },

  {
    id: 211,
    title: "React Developer",
    company: "Mindtree",
    location: "Bengaluru",
    salary: "5-9 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["React","Redux","JavaScript","HTML"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "5 days ago",
    logo: "/logos/Mindtree.png"
  },

  {
    id: 212,
    title: "React Developer",
    company: "LTIMindtree",
    location: "Pune",
    salary: "6-11 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["React","TypeScript","Redux","REST API"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "3 days ago",
    logo: "/logos/Itimindtree.png"
  },

  {
    id: 213,
    title: "React Developer",
    company: "Oracle India",
    location: "Hyderabad",
    salary: "10-18 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["React","Micro Frontend","JavaScript","Cloud"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2 days ago",
    logo: "/logos/Oracle.png"
  },

  {
    id: 214,
    title: "React Developer",
    company: "Paytm",
    location: "Noida",
    salary: "7-12 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["React","Redux","JavaScript","API Integration"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "4 days ago",
    logo: "/logos/Paytm.png"
  },

  {
    id: 215,
    title: "React Developer",
    company: "PhonePe",
    location: "Bengaluru",
    salary: "8-15 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["React","TypeScript","Redux","Kafka"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "Today",
    logo: "/logos/Phonepe.png"
  },

  {
    id: 216,
    title: "React Developer",
    company: "Flipkart",
    location: "Bengaluru",
    salary: "10-18 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["React","Next.js","Redux","Performance Optimization"],
    status: "close",
    featured: true,
    topCompany: true,
    postedOn: "3 days ago",
    logo: "/logos/Flipkart.jpg"
  },

  {
    id: 217,
    title: "React Developer",
    company: "Zensar Technologies",
    location: "Pune",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["React","JavaScript","CSS","Bootstrap"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "6 days ago",
    logo: "/logos/ZensarTechnologies.jpg"
  },

  {
    id: 218,
    title: "React Developer",
    company: "Mphasis",
    location: "Bengaluru",
    salary: "5-8 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["React","JavaScript","HTML","CSS"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "1 week ago",
    logo: "/logos/Mphasis.png"
  },

  {
    id: 221,
    title: "Sales Executive",
    company: "HDFC Bank",
    location: "Mumbai",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Sales","Communication","Lead Generation","CRM"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "Today",
    logo: "/logos/HDFC.jpg"
  },

  {
    id: 222,
    title: "Sales Executive",
    company: "ICICI Bank",
    location: "Hyderabad",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Sales","Field Work","Customer Handling","CRM"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "1 day ago",
    logo: "/logos/ICICI.jpg"
  },

  {
    id: 223,
    title: "Sales Executive",
    company: "Axis Bank",
    location: "Bengaluru",
    salary: "3-5 LPA",
    experience: "0-2 Years",
    type: "Full Time",
    skills: ["Sales","Banking Products","Communication","Lead Generation"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2 days ago",
    logo: "/logos/Axis Bank.jpg"
  },

  {
    id: 224,
    title: "Sales Executive",
    company: "Flipkart",
    location: "Bengaluru",
    salary: "4-7 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["E-commerce Sales","CRM","Negotiation","Communication"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "Today",
    logo: "/logos/Flipkart.jpg"
  },

  {
    id: 225,
    title: "Sales Executive",
    company: "Amazon India",
    location: "Hyderabad",
    salary: "5-9 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Sales","Account Management","CRM","Negotiation"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "Today",
    logo: "/logos/Amazon.png"
  },

  {
    id: 226,
    title: "Sales Executive",
    company: "Paytm",
    location: "Noida",
    salary: "4-8 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Sales","Field Sales","Lead Generation","Communication"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "3 days ago",
    logo: "/logos/Paytm.png"
  },

  {
    id: 227,
    title: "Sales Executive",
    company: "Zomato",
    location: "Gurgaon",
    salary: "4-7 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["B2B Sales","Client Acquisition","CRM","Negotiation"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "1 day ago",
    logo: "/logos/Zomato.png"
  },

  {
    id: 228,
    title: "Sales Executive",
    company: "Swiggy",
    location: "Bengaluru",
    salary: "4-7 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Sales","Client Handling","Field Sales","Communication"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2 days ago",
    logo: "/logos/Swiggy.png"
  },

  {
    id: 229,
    title: "Sales Executive",
    company: "BYJU'S",
    location: "Bengaluru",
    salary: "5-10 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Inside Sales","Cold Calling","CRM","Communication"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "1 week ago",
    logo: "/logos/Byjus.png"
  },

  {
    id: 230,
    title: "Sales Executive",
    company: "Unacademy",
    location: "Bengaluru",
    salary: "5-9 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Sales","Lead Conversion","CRM","Communication"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "Today",
    logo: "/logos/Unacademy.png"
  },

  {
    id: 231,
    title: "Sales Executive",
    company: "HCL Technologies",
    location: "Noida",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["IT Sales","CRM","Communication","Client Handling"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "4 days ago",
    logo: "/logos/HCL.png"
  },

  {
    id: 232,
    title: "Sales Executive",
    company: "Tech Mahindra",
    location: "Pune",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Sales","Lead Generation","CRM","Communication"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "3 days ago",
    logo: "/logos/TechMahindra.png"
  },

  {
    id: 233,
    title: "Sales Executive",
    company: "Infosys BPM",
    location: "Bengaluru",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Sales Support","CRM","Communication","Reporting"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2 days ago",
    logo: "/logos/Infosys.png"
  },

  {
    id: 234,
    title: "Sales Executive",
    company: "Accenture",
    location: "Gurgaon",
    salary: "4-8 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["B2B Sales","CRM","Negotiation","Communication"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "Today",
    logo: "../logos/Accenture.png"
  },

  {
    id: 235,
    title: "Sales Executive",
    company: "TCS",
    location: "Chennai",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Sales Support","CRM","Communication","Reporting"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "4 days ago",
    logo: "/logos/TCS.jpg"
  },

  {
    id: 236,
    title: "Sales Executive",
    company: "Wipro",
    location: "Hyderabad",
    salary: "3-5 LPA",
    experience: "0-2 Years",
    type: "Full Time",
    skills: ["Sales","CRM","Communication","Client Handling"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "1 week ago",
    logo: "/logos/Wipro.png"
  },

  {
    id: 237,
    title: "Sales Executive",
    company: "Genpact",
    location: "Mumbai",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["Inside Sales","CRM","Communication","Lead Generation"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "5 days ago",
    logo: "/logos/Genpact.png"
  },

  {
    id: 238,
    title: "Sales Executive",
    company: "Freshworks",
    location: "Chennai",
    salary: "4-8 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["SaaS Sales","CRM","Negotiation","Communication"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2 days ago",
    logo: "/logos/Freshworks.jpg"
  },

  {
    id: 239,
    title: "Sales Executive",
    company: "Capgemini",
    location: "Mumbai",
    salary: "3-6 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["IT Sales","CRM","Communication","Client Acquisition"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "3 days ago",
    logo: "/logos/Capgemini.png"
  },

  {
    id: 241,
    title: "Software Engineer",
    company: "Tata Consultancy Services",
    location: "Hyderabad",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Java","Python","DSA","SQL"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-16",
    logo: "/logos/TCS.png"
  },

  {
    id: 242,
    title: "Software Engineer",
    company: "Infosys",
    location: "Bengaluru",
    salary: "6-10 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","React","SQL"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-16",
    logo: "/logos/Infosys.png"
  },

  {
    id: 243,
    title: "Software Engineer",
    company: "Wipro",
    location: "Pune",
    salary: "4-8 LPA",
    experience: "0-3 Years",
    type: "Full Time",
    skills: ["C++","Java","HTML","CSS"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-15",
    logo: "/logos/Wipro.png"
  },

  {
    id: 244,
    title: "Software Engineer",
    company: "HCL Technologies",
    location: "Chennai",
    salary: "6-11 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Java","Microservices","AWS","SQL"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-15",
    logo: "/logos/HCL.png"
  },

  {
    id: 245,
    title: "Software Engineer",
    company: "Tech Mahindra",
    location: "Noida",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Python","Java","REST API","Git"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-14",
    logo: "/logos/TechMahindra.png"
  },

  {
    id: 246,
    title: "Software Engineer",
    company: "Capgemini",
    location: "Mumbai",
    salary: "6-10 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","React","SQL"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-14",
    logo: "/logos/Capgemini.png"
  },

  {
    id: 247,
    title: "Software Engineer",
    company: "Cognizant",
    location: "Kolkata",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Java","Python","SQL","HTML"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-13",
    logo: "/logos/Cognizant.jpg"
  },

  {
    id: 248,
    title: "Software Engineer",
    company: "Accenture",
    location: "Gurgaon",
    salary: "7-13 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Java","Cloud","Microservices","AWS"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-13",
    logo: "/logos/Accenture.png"
  },

  {
    id: 249,
    title: "Software Engineer",
    company: "IBM India",
    location: "Hyderabad",
    salary: "8-14 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["Java","AI/ML","Cloud","Kubernetes"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-12",
    logo: "/logos/IBM.png"
  },

  {
    id: 250,
    title: "Software Engineer",
    company: "Amazon India",
    location: "Bengaluru",
    salary: "12-25 LPA",
    experience: "3-7 Years",
    type: "Full Time",
    skills: ["Java","System Design","AWS","Microservices"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-12",
    logo: "/logos/Amazon.png"
  },

  {
    id: 251,
    title: "Software Engineer",
    company: "Zoho",
    location: "Chennai",
    salary: "6-10 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Java","Python","SQL","REST API"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-11",
    logo: "/logos/Zoho.png"
  },

  {
    id: 252,
    title: "Software Engineer",
    company: "Mindtree",
    location: "Bengaluru",
    salary: "5-9 LPA",
    experience: "1-4 Years",
    type: "Full Time",
    skills: ["Java","React","SQL","Git"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-11",
    logo: "/logos/Mindtree.png"
  },

  {
    id: 253,
    title: "Software Engineer",
    company: "LTIMindtree",
    location: "Pune",
    salary: "6-11 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","Microservices","SQL"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-10",
    logo: "/logos/Itimindtree.png"
  },

  {
    id: 254,
    title: "Software Engineer",
    company: "Oracle India",
    location: "Hyderabad",
    salary: "10-18 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["Java","Cloud","Database","Microservices"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-10",
    logo: "/logos/Oracle.png"
  },

  {
    id: 255,
    title: "Software Engineer",
    company: "Paytm",
    location: "Noida",
    salary: "7-12 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["Java","Python","Redis","Microservices"],
    status: "open",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-09",
    logo: "/logos/Paytm.png"
  },

  {
    id: 256,
    title: "Software Engineer",
    company: "PhonePe",
    location: "Bengaluru",
    salary: "8-15 LPA",
    experience: "2-5 Years",
    type: "Full Time",
    skills: ["Java","Kafka","Microservices","System Design"],
    status: "open",
    featured: true,
    topCompany: true,
    postedOn: "2026-06-09",
    logo: "/logos/Phonepe.png"
  },

  {
    id: 257,
    title: "Software Engineer",
    company: "Flipkart",
    location: "Bengaluru",
    salary: "10-18 LPA",
    experience: "3-6 Years",
    type: "Full Time",
    skills: ["Java","System Design","Microservices","Kafka"],
    status: "close",
    featured: false,
    topCompany: true,
    postedOn: "2026-06-08",
    logo: "/logos/Flipkart.jpg"
  },

  {
    id: 258,
    title: "Software Engineer",
    company: "Zensar Technologies",
    location: "Pune",
    salary: "5-9 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Java","SQL","Spring Boot","HTML"],
    status: "open",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-08",
    logo: "/logos/ZensarTechnologies.jpg"
  },

  {
    id: 259,
    title: "Software Engineer",
    company: "Persistent Systems",
    location: "Nagpur",
    salary: "6-10 LPA",
    experience: "2-4 Years",
    type: "Full Time",
    skills: ["Java","Spring Boot","React","MongoDB"],
    status: "open",
    featured: true,
    topCompany: false,
    postedOn: "2026-06-07",
    logo: "/logos/PWS.png"
  },

  {
    id: 260,
    title: "Software Engineer",
    company: "Mphasis",
    location: "Bengaluru",
    salary: "5-8 LPA",
    experience: "1-3 Years",
    type: "Full Time",
    skills: ["Java","Python","SQL","Git"],
    status: "close",
    featured: false,
    topCompany: false,
    postedOn: "2026-06-07",
    logo: "/logos/Mphasis.png"
  }
];

export default jobs;